# Spring Boot MySQL\u914D\u7F6E\u793A\u4F8B

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-react?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
